feature#17 fixed
at-dungnh/ePromotions pull request #100
Opened 2016-12-12 07:05 UTC by at-tienpd

-Display Promotion
-Create Promotion
-Edit Promotion
-Delete Promotion

2016-12-12 07:25 UTC, dzungnguyenh requested changes
please check and follow other about code convention and handle with actions

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +
[rank C] please remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +
[rank C] please remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +
[rank C] please remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +        Session::flash('message', 'Successfully deleted promotion!');
[rank C] please add this message in language file and remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on resources/views/promotion/create.blade.php
> +        <label for="title_store">Title</label>
[rank C] please define all labels in language files

2016-12-12 07:25 UTC, at-dungnh commented on resources/views/promotion/edit.blade.php
> +        <label for="title_edit">Title</label>
[rank C] please define all labels in language files

2016-12-12 07:25 UTC, at-dungnh commented on resources/views/promotion/list.blade.php
> +  <h3>List Promotion</h3>
[rank C] please define all labels in language files

2016-12-12 07:25 UTC, at-dungnh commented on routes/web.php
> +
[rank C] please remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on resources/views/promotion/edit.blade.php
> +        <input type="datetime-local" class="form-control" id="start-date" name="date_start" value="{{ old('date_start',gmdate('Y-m-d\TH:i',strtotime($promotion->date_start))) }}">
[rank C] format datetime should be define as constant in config

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +        $this->promotion->delete($id);
[rank A] what's happen if $id cannot found? Please refer other to handle in this case

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +        $this->promotion->update($promotion, $id);
[rank C] please add this message in language file and remove blank line

2016-12-12 07:25 UTC, at-dungnh commented on app/Http/Controllers/Bussiness/PromotionController.php
> +        $this->promotion->update($promotion, $id);
[rank A] what's happen if $id cannot found? Please refer other to handle in this case

2016-12-12 10:00 UTC, at-tienpd commented on app/Http/Controllers/Bussiness/PromotionController.php
> +        $this->promotion->delete($id);
The handle executed in BaseRepository file. So, i'm don't repeat myself in my PromotionController file.

2016-12-12 10:09 UTC, dzungnguyenh requested changes

2016-12-12 10:09 UTC, at-dungnh commented on resources/views/promotion/create.blade.php
> +    <input type="hidden" name="product_id" value="1">
[rank A] what does product_id hidden means?

2016-12-12 10:18 UTC, at-tienpd commented on resources/views/promotion/create.blade.php
> +    <input type="hidden" name="product_id" value="1">
This used test. Because it relationship with product table. I need product_id to create promotion for this product.

2016-12-13 02:08 UTC, dzungnguyenh requested changes
please check my comment

2016-12-13 02:08 UTC, at-dungnh commented on resources/views/promotion/create.blade.php
> +    <input type="hidden" name="product_id" value="1">
in that case, I think it wrong, you can try create some products in db directly and select it when create promotion. We don't use hard code to checking anything.

2016-12-14 02:39 UTC, closed without merging